print("TAXI WIEN - Fahrpreisrechner")
print("********************************")
print("*==============================*")
print("*                              *")
print("*  *****  ***  *   *  *        *")
print("*    *   *   *  * *   *        *")
print("*    *   *****   *    *        *")
print("*    *   *   *  * *   *        *")
print("*    *   *   * *   *  *        *")
print("*                              *")
print("* Willkommen beim Taxirechner  *")
print("*==============================*")
print("********************************")
km = input("Bitte geben Sie die gefahrenen Kilometer ein: ")
euro = 3 * float(km)
print(f"Der Fahrpreis beträgt {euro} Euro.")
input("Zum Beenden Enter klicken.")